name: template_flutter
description: Cinnamon Agency starter template for Flutter applications

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  ###
  # DEPENDENCIES
  ###
  alice: 0.2.5
  camera: 0.10.0+1
  connectivity_plus: 2.3.6+1
  device_info_plus: 4.1.2
  dio: 4.0.6
  flutter_screenutil: 5.5.4
  flutter_staggered_animations: 1.1.1
  flutter_svg: 1.1.4
  geolocator: 9.0.2
  get: 4.6.5
  get_storage: 2.0.3
  google_fonts: 3.0.1
  hive: 2.2.3
  hive_flutter: 1.1.0
  image_picker: 0.8.5+3
  intl: 0.17.0
  just_audio: 0.9.29
  loading_animation_widget: 1.2.0+3
  location: 4.4.0
  logger_fork: 1.2.0
  logger_flutter_fork: 1.2.0
  package_info_plus: 1.4.3+1
  path_provider: 2.0.11
  permission_handler: 10.0.2
  url_launcher: 6.1.5
  video_player: 2.4.7

  # FIREBASE
  firebase_core: 1.24.0
  firebase_auth: 3.11.0
  cloud_firestore: 3.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  ###
  # DEV DEPENDENCIES
  ###
  build_runner: 2.2.0
  flutter_launcher_icons: 0.10.0
  flutter_native_splash: 2.2.8
  hive_generator: 1.1.3

dependency_overrides:
  ffi: 2.0.1
  permission_handler: 10.0.2

# Trigger code generation
# flutter packages pub run build_runner build --delete-conflicting-outputs

# Configuration for 'flutter_launcher_icons'
# Run icon generation with 'flutter pub run flutter_launcher_icons:main'
flutter_icons:
  android: true
  ios: true
  image_path: 'assets/icon.png'
  adaptive_icon_background: '#FFFFFF'
  adaptive_icon_foreground: 'assets/icon.png'

# Configuration for 'flutter_native_splash'
# Run splash screen generation with 'flutter pub run flutter_native_splash:create'
flutter_native_splash:
  android: true
  ios: true
  color: '#FFFFFF'
  image: 'assets/icon.png'

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/countries_json.json
